### ISSUE TITLE
Add Wheels to PyPI Packages

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-hub#29]
As per the Pyodide Documentation ["Why can’t Micropip find a “pure Python wheel” for a package?"](https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package) packages for installation with `micropip` must have pure python wheels (`*py3-none-any.whl`) on PyPI.

 - [x] 🛞 [bw2data==4.0.dev25](https://pypi.org/project/bw2data/4.0.dev25/)
 - [x] 🛞 [bw2io==0.9.dev21](https://pypi.org/project/bw2io/0.9.dev21/)
 - [x] 🛞 [bw2calc==2.0.dev14](https://pypi.org/project/bw2calc/2.0.dev14/)
 - [x] 🛞 [stats-arrays==0.6.5](https://pypi.org/project/stats-arrays/0.6.5/)
 - [x] 🛞 [matrix-utils==0.2.5](https://pypi.org/project/matrix-utils/0.2.5/)
 - [x] 🛞 [bw2analyzer==0.11.7](https://pypi.org/project/bw2analyzer/0.11.7/)

**Comment by michaelweinold** [comment]
...third party packages without wheels (returned by `await micropip.install('bw2XXX', keep_going=True)`:

 - [ ] docopt
 - [ ] unicodecsv
 - [ ] psutil

**Comment by cmutel** [comment]
Can you figure out who is requesting these last ones? We can't add wheels to third party apps, and I thought we got rid of docopt, unicodecsv, and psutil already?

**Comment by michaelweinold** [comment]
Tested this in a separate issue: https://github.com/brightway-lca/brightway-hub/issues/30, where my main finding was that:

> ...magically worked the second time?!

I'll ping you when I get stuck again. Looks good for now, but breakfast will take precedence over debugging during the next hour 😇
